import {before,after,beforeEach,test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {initializeTestEnvironment,assertFails} from '@firebase/rules-unit-testing';
import {doc,setDoc,getDoc,getDocs,collection,deleteDoc,writeBatch,serverTimestamp} from 'firebase/firestore';
import {createTeamStore} from '../../src/firebase-db.js';
import {createTrolley} from '../../src/trolleys.js';
const initialTrolley=createTrolley('Trolley 01');
let env;
const member={displayName:'Test Technician',code:'TT',role:'technician',active:true};
const admin={displayName:'Test Administrator',code:'TA',role:'admin',active:true};
const sample=(id='equipment-1',serial='ABC123')=>({id,serial,model:'Test model',manufacturer:'Test maker',date:'2026-10-09',description:'Monitor',source:'Storage',reason:'EOL',trolley:'Trolley 01',trolleyId:initialTrolley.id,barcode:'N/A',etch:'N/A',asset:'N/A',technician:'TT'});
const context=uid=>env.authenticatedContext(uid).firestore();
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-decompro',firestore:{host:'127.0.0.1',port:8085,rules:await readFile('database/firestore.rules','utf8')}});});
after(async()=>{await env?.cleanup();});
beforeEach(async()=>{await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{await setDoc(doc(c.firestore(),'teams/college-it/members/tech'),member);await setDoc(doc(c.firestore(),'teams/college-it/members/admin'),admin);});await createTeamStore(context('tech'),'tech','college-it',member).writeTrolley(initialTrolley);});
test('unauthenticated and non-member access is denied; a member cannot promote themselves',async()=>{
 await assertFails(getDocs(collection(env.unauthenticatedContext().firestore(),'teams/college-it/equipment')));
 await assertFails(getDocs(collection(context('outsider'),'teams/college-it/references')));
 await assertFails(setDoc(doc(context('tech'),'teams/college-it/members/tech'),{...member,role:'admin'}));
});
test('records and immutable revisions commit together; ordinary duplicate serials are rejected',async()=>{
 const db=context('tech'),client=createTeamStore(db,'tech','college-it',member);
 await client.write(sample());
 const row=await getDoc(doc(db,'teams/college-it/equipment/equipment-1'));assert.equal(row.data().createdBy,'tech');assert.equal(row.data().version,1);
 const audit=await getDocs(collection(db,'teams/college-it/equipment/equipment-1/revisions'));assert.equal(audit.size,1);
 await assertFails(deleteDoc(audit.docs[0].ref));
 await assert.rejects(client.write(sample('equipment-2')),/already recorded/);
 assert.equal((await getDoc(doc(db,'teams/college-it/equipment/equipment-2'))).exists(),false);
 await assertFails(setDoc(doc(db,'teams/college-it/equipment/forged'),{...row.data(),payload:{...sample('forged'),technician:'Someone else'}}));
});
test('conflicting edits are rejected and removal retains audit history',async()=>{
 const db=context('tech'),first=createTeamStore(db,'tech','college-it',member),second=createTeamStore(context('admin'),'admin','college-it',admin);
 await first.write(sample());await first.write({...sample(),model:'Corrected model'},1);
 await assert.rejects(second.write({...sample(),model:'Stale model'},1),/Another technician/);
 await first.write({...sample(),model:'Corrected model'},2,{deleted:true});
 assert.equal((await first.load()).items.length,0);assert.equal((await getDocs(collection(db,'teams/college-it/equipment/equipment-1/revisions'))).size,3);
 await assertFails(deleteDoc(doc(db,'teams/college-it/equipment/equipment-1')));
});
test('serial index escaping is collision-free and spreadsheet examples are idempotent',async()=>{
 const client=createTeamStore(context('tech'),'tech','college-it',member);
 await client.write(sample('with-slash','AB/C~D'));await client.write(sample('literal-escape','AB~sC~D'));
 const facts=[{serial:'0001',model:'Test model',manufacturer:'Test maker',source:'Excel'}];await client.importExamples(facts);await client.importExamples(facts);
 assert.equal((await client.load()).examples.length,1);
});

test('trolley references, inventory and collection history commit together and reject later equipment changes',async()=>{
 const {createTrolley}=await import('../../src/trolleys.js');
 const db=context('tech'),client=createTeamStore(db,'tech','college-it',member);
 const trolley=createTrolley('Collection 01');await client.writeTrolley(trolley);
 const item={...sample(),trolley:trolley.name,trolleyId:trolley.id};await client.write(item);
 const changed={...trolley,department:'Helpdesk Annex'};await client.writeTrolley(changed,1);
 await assert.rejects(client.writeTrolley({...trolley,department:'Stale department'},1),/Another technician/);
 const legacy={...sample('legacy-item','LEGACY123'),trolley:trolley.name,trolleyId:trolley.id};await client.write(legacy);
 await env.withSecurityRulesDisabled(async c=>{const row=doc(c.firestore(),'teams/college-it/equipment/legacy-item'),data=(await getDoc(row)).data();delete data.payload.trolleyId;await setDoc(row,data);});
 const collected={...changed,status:'collected',company:'Test supplier',collectedAt:new Date().toISOString(),collectedBy:'TT'};
 await client.writeTrolley(collected,2);
 const records=await client.load();assert.equal(records.trolleys.find(t=>t.id===trolley.id).status,'collected');assert.equal(records.items.length,2);assert.equal(records.items.find(i=>i.id==='legacy-item').trolleyId,trolley.id);
 assert.equal(records.trolleys.find(t=>t.id===trolley.id).reference,trolley.reference);
 await assert.rejects(client.write({...item,id:'equipment-after-collection',serial:'LATE123'}),/collected/);
 await assert.rejects(client.write({...item,model:'Changed after collection'},1),/collected/);
 await assert.rejects(client.write(item,1,{deleted:true}),/collected/);
 await assert.rejects(client.writeTrolley(changed,3),/history is locked/);
 const equipmentRow=doc(db,'teams/college-it/equipment/equipment-1'),before=(await getDoc(equipmentRow)).data(),revisionId='forged-change';
 const after={...before,payload:{...before.payload,model:'Bypass attempt'},version:2,updatedAt:serverTimestamp(),revisionId};
 const forged=writeBatch(db);forged.set(equipmentRow,after);forged.set(doc(equipmentRow,'revisions',revisionId),{actor:'tech',before,after,action:'edit',at:serverTimestamp()});await assertFails(forged.commit());
 const revisions=await getDocs(collection(db,`teams/college-it/trolleys/${trolley.id}/revisions`));assert.equal(revisions.size,3);
 await assertFails(deleteDoc(revisions.docs[0].ref));await assertFails(deleteDoc(doc(db,`teams/college-it/trolleys/${trolley.id}`)));
 await assertFails(getDocs(collection(env.unauthenticatedContext().firestore(),'teams/college-it/trolleys')));
});
