import { fields, headers, supplierRow, duplicateSerial } from './data';
import './style.css';
const key = 'decompro.v1';
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
let state = { profiles:[{name:'Jawad',code:'JA'}], active:'JA', defaults:{date:today(),description:'Monitor',manufacturer:'',source:'Storage',reason:'EOL',trolley:'Trolley 01'}, items:[], draft:{}, step:0, voice:true };
let storageError = '', notice = '', scanning = false, lastEmpty = 0;
try { const saved=localStorage.getItem(key); if(saved) { const parsed=JSON.parse(saved); if(!Array.isArray(parsed.items)||!Array.isArray(parsed.profiles)||!parsed.defaults||!parsed.draft||!Number.isInteger(parsed.step)||parsed.step<0||parsed.step>fields.length) throw Error(); state={...state,...parsed}; } } catch { storageError='Saved data could not be loaded. Export any visible records before continuing. Storage has been paused to protect the saved data.'; }
const escape = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist() { if(storageError) return false; try { localStorage.setItem(key,JSON.stringify(state)); return true; } catch { storageError='Browser storage is unavailable or full. Export your records now; changes may be lost on refresh.'; render(); return false; } }
function speak(text) { if(!state.voice || !('speechSynthesis' in window)) return; speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text); u.lang='en-GB'; u.rate=.92; speechSynthesis.speak(u); }
function prompt() { speak(state.step<fields.length ? `Next, ${fields[state.step][1]}` : 'Review equipment. Press Enter to save and place it in the trolley.'); }
function focus() { if(scanning) document.querySelector('#scan')?.focus(); }
function render() {
 const current=fields[state.step]; const profile=state.profiles.find(p=>p.code===state.active);
 document.querySelector('#app').innerHTML=`
 <aside><a class="brand" href="#">▧ <span>Decom<span class="brand-light">Pro</span></span></a><div class="workspace">IT OPERATIONS</div><div class="nav active">▦ &nbsp; Scan station</div><a class="nav" href="#inventory">☷ &nbsp; Collection register <span>${state.items.length}</span></a><div class="aside-bottom"><span class="dot"></span> Local workspace<p>Records stay on this browser.<br>Export after each session.</p></div></aside>
 <main><header><div><div class="eyebrow">EQUIPMENT DECOMMISSIONING</div><h1>Scan. Cage. Done.</h1><p>A clear next step for every piece of equipment.</p></div><div class="profile"><label for="profile">Technician profile</label><select id="profile">${state.profiles.map(p=>`<option value="${escape(p.code)}" ${p.code===state.active?'selected':''}>${escape(p.name)} · ${escape(p.code)}</option>`).join('')}</select><button class="text-button" id="add-profile">+ Add technician</button></div></header>
 ${storageError?`<div class="alert error" role="alert">${escape(storageError)}</div>`:''}${notice?`<div class="alert" role="status">${escape(notice)}</div>`:''}
 <div class="stats"><div><span>READY FOR COLLECTION</span><strong>${state.items.length}<small> items recorded</small></strong></div><div><span>CURRENT TROLLEY</span><strong>${escape(state.defaults.trolley)}</strong></div><div><span>DISPOSAL RECORDED BY</span><strong>${escape(profile?.name||'Select technician')}<small>${escape(profile?.code||'')}</small></strong></div></div>
 <div class="station-layout"><section class="card station"><div class="section-top"><span class="eyebrow">SCAN STATION</span><button id="voice" class="pill">${state.voice?'◖ Voice on':'◖ Voice off'}</button></div><div class="steps">${fields.map((f,i)=>`<button class="step ${i===state.step?'current':''} ${i<state.step?'complete':''}" data-step="${i}" ${i>state.step?'disabled':''}><span>${i<state.step?'✓':i+1}</span>${escape(f[1].replace(' number',''))}</button>`).join('')}</div>
 <div class="scan-icon">⌁</div><div class="scan-label">${current?`FIELD ${state.step+1} OF ${fields.length}`:'READY TO RECORD'}</div><h2>${current?escape(current[1]):'Review this equipment'}</h2><p>${current?'Scan the label or type its value, then press Enter.':'Check the values below, then save this item to the collection register.'}</p>
 ${current?`<form id="scan-form"><label class="sr-only" for="scan">${escape(current[1])}</label><input id="scan" autocomplete="off" spellcheck="false" placeholder="Waiting for a scan…" value="${escape(state.draft[current[0]]||'')}"><button class="primary" type="submit">Capture value →</button></form><div class="scan-actions"><button id="start" class="text-button">${scanning?'↻ Repeat spoken prompt':'▶ Start scanning'}</button><button id="skip" class="secondary">Skip · N/A</button></div><div class="hint">Double-click the scanner trigger (two empty Enter presses) to skip.</div>`:`<button id="save" class="primary wide">Save item & start next →</button>`}
 <div class="captured">${fields.filter(f=>state.draft[f[0]]).map(([k,label])=>`<div><span>${escape(label)}</span><strong>${escape(state.draft[k])}</strong></div>`).join('')||'<span>Captured values will appear here.</span>'}</div><div class="station-footer"><button id="back" class="text-button" ${state.step===0?'disabled':''}>← Previous field</button><button id="reset" class="text-button">Clear current item</button></div></section>
 <section class="card defaults"><div class="eyebrow">BATCH DEFAULTS</div><h2>Set once. Keep scanning.</h2><p>Applied to each item when you save it.</p><form id="defaults">${[['date','Disposal date','date'],['description','Equipment description','text'],['manufacturer','Manufacturer','text'],['source','Taken from','text'],['reason','Reason for disposal','text'],['trolley','Caged trolley','text']].map(([k,label,type])=>`<label for="default-${k}">${label}</label><input id="default-${k}" name="${k}" type="${type}" value="${escape(state.defaults[k])}" required>`).join('')}<button class="secondary wide" type="submit">Apply batch defaults</button></form><div class="note">Technician initials automatically fill <strong>Who disposed of it?</strong> in your Excel export.</div></section></div>
 <section id="inventory" class="card register"><div class="section-top"><div><div class="eyebrow">COLLECTION REGISTER</div><h2>Ready for the next collection <span class="count">${state.items.length}</span></h2></div><button id="export" class="primary" ${!state.items.length?'disabled':''}>↓ Export Excel</button></div><div class="table-wrap"><table><thead><tr><th>Equipment / model</th><th>Serial number</th><th>Asset number</th><th>Trolley</th><th>Technician</th><th></th></tr></thead><tbody>${state.items.slice().reverse().map(i=>`<tr><td><strong>${escape(i.description)}</strong><span>${escape(i.manufacturer)} · ${escape(i.model)}</span></td><td>${escape(i.serial)}</td><td>${escape(i.asset)}</td><td><span class="tag">${escape(i.trolley)}</span></td><td>${escape(i.technician)}</td><td><button class="text-button" data-delete="${escape(i.id)}" aria-label="Delete item ${escape(i.serial)}">Remove</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Your first scanned item will appear here.<br><span>Set your batch defaults, then start scanning.</span></td></tr>'}</tbody></table></div><div class="register-footer">Excel matches all 17 supplier columns. Finance fields stay blank. Trolley is tracked here only.</div></section>
 <footer>DecomPro · Less clicking. More clearing.</footer></main><dialog id="profile-dialog"><form id="profile-form"><h2>Add a technician</h2><p>Local profiles identify records; they are not secure sign-in accounts.</p><label for="name">Name</label><input id="name" name="name" required maxlength="60"><label for="code">Disposal initials</label><input id="code" name="code" required maxlength="12"><div class="dialog-actions"><button class="secondary" type="button" id="cancel-profile">Cancel</button><button class="primary">Save profile</button></div><p id="profile-error" role="alert"></p></form></dialog>`;
 bind(); focus();
}
function capture(value) { value=value.trim(); if(!value || state.step>=fields.length) return; state.draft[fields[state.step][0]]=value; state.step++; lastEmpty=0; notice=''; persist(); render(); prompt(); }
function saveItem() {
 const profile=state.profiles.find(p=>p.code===state.active);
 if(!profile) {notice='Choose a technician first.';render();return;}
 if(Object.values(state.defaults).some(v=>!v.trim())) {notice='Complete and apply all batch defaults first.';render();return;}
 if(fields.some(([k])=>!state.draft[k])) return;
 if(duplicateSerial(state.items,state.draft.serial)){notice='This serial number is already in the register. Check the current item before saving.';render();speak(notice);return;}
 state.items.push({...state.defaults,...state.draft,technician:profile.code,id:crypto.randomUUID()}); state.draft={};state.step=0;notice='Item recorded. Place it in the caged trolley.';persist();render();speak('Item recorded. Place it in the caged trolley. Next, model number.');
}
function bind() {
 document.querySelector('#profile').onchange=e=>{state.active=e.target.value;persist();render();};
 document.querySelector('#voice').onclick=()=>{state.voice=!state.voice;persist();render();if(state.voice)prompt();else window.speechSynthesis?.cancel();};
 document.querySelector('#start')?.addEventListener('click',()=>{scanning=true;focus();prompt();});
 document.querySelector('#scan-form')?.addEventListener('submit',e=>{e.preventDefault();scanning=true;const value=document.querySelector('#scan').value;if(value.trim())capture(value);else {const now=Date.now();if(lastEmpty&&now-lastEmpty<700){capture('N/A');}else {lastEmpty=now;notice='Press Enter again within 0.7 seconds to skip this field.';document.querySelector('.hint').textContent=notice;}}});
 document.querySelector('#skip')?.addEventListener('click',()=>{scanning=true;capture('N/A');});
 document.querySelector('#save')?.addEventListener('click',saveItem);
 document.querySelector('#back').onclick=()=>{if(state.step>0){state.step--;lastEmpty=0;persist();render();prompt();}};
 document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{state.step=Number(b.dataset.step);lastEmpty=0;persist();render();prompt();});
 document.querySelector('#reset').onclick=()=>{if(Object.keys(state.draft).length&&!confirm('Clear the current unsaved item?'))return;state.draft={};state.step=0;lastEmpty=0;persist();render();prompt();};
 document.querySelector('#defaults').onsubmit=e=>{e.preventDefault();state.defaults=Object.fromEntries([...new FormData(e.target)].map(([k,v])=>[k,v.trim()]));notice='Batch defaults applied.';persist();render();};
 document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(!confirm('Remove this item from the collection register?'))return;state.items=state.items.filter(i=>i.id!==b.dataset.delete);persist();render();});
 document.querySelector('#export').onclick=exportExcel;
 document.querySelector('#add-profile').onclick=()=>document.querySelector('#profile-dialog').showModal();
 document.querySelector('#cancel-profile').onclick=()=>document.querySelector('#profile-dialog').close();
 document.querySelector('#profile-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),name=f.get('name').trim(),code=f.get('code').trim().toUpperCase();if(!name||!code||state.profiles.some(p=>p.code===code)){document.querySelector('#profile-error').textContent='Enter a name and unique disposal initials.';return;}state.profiles.push({name,code});state.active=code;persist();render();};
}
async function exportExcel() { try {const {default:ExcelJS}=await import('exceljs');const workbook=new ExcelJS.Workbook();const sheet=workbook.addWorksheet('Sheet1');sheet.addRow(headers);for(const item of state.items)sheet.addRow(supplierRow(item));sheet.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF164E3D'}};sheet.getRow(1).height=30;sheet.columns.forEach((c,i)=>c.width=i===1?28:22);sheet.getColumn(1).numFmt='dd/mm/yyyy';sheet.views=[{state:'frozen',ySplit:1}];sheet.autoFilter='A1:Q1';const data=await workbook.xlsx.writeBuffer();const url=URL.createObjectURL(new Blob([data],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const a=document.createElement('a');a.href=url;a.download=`Decom-${today()}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice='Excel exported. Keep this file as your session backup.';render();}catch {notice='Export failed. Your records are still in the register; please try again.';render();} }
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&state.step===fields.length&&!document.querySelector('dialog[open]')&&!['INPUT','SELECT','BUTTON','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();saveItem();}});
render();
